name: Deploy Fullstack App

on:
  push:
    branches: [main]
    paths:
      - "client/**"
      - "server/**"
  pull_request:
    branches: [main]
    paths:
      - "client/**"
      - "server/**"

jobs:
  deploy-frontend:
    name: Deploy React Client to Vercel
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel --prod --yes --token=$VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

  deploy-backend:
    name: Deploy Node Backend to EC2
    runs-on: ubuntu-latest
    needs: deploy-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy code to EC2 via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          source: "server/*"
          target: "~/healthcare-portal/server"

      - name: SSH into EC2 and restart backend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/healthcare-portal/server
            npm install
            pm2 restart all || pm2 start index.js --name backend
